<?php

return [
    'PRACTICE_ALL' => 0,
    'PRACTICE_THIS_WEEK' => 1,
    'PRACTICE_THIS_MONTH' => 2,
    'PRACTICE_LAST_WEEK' => 3,
    'PRACTICE_LAST_MONTH' => 4,
    'PRACTICE_3_RECENTLY' => 5,
    'PRACTICE_7_RECENTLY' => 6,
    'PRACTICE_10_RECENTLY' => 7,
];
